# -*- coding: utf-8 -*-
"""Drone_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15P4Vb049WciL1PhVT_dMXnWVEpmK1WCN

## **Environment Setup**

This imports the mathematical libraries, widget frames, and layout components required to render the interactive UI panels and graphical animations
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# Configure matplotlib to output static plot figures cleanly inline
# %matplotlib inline

"""# **Task 1 – Drone Altitude PID Control**

The drone must navigate to and hover stably at a target altitude of 10 meters. A dynamic wind disturbance force steps into the system loop after exactly 6 seconds to evaluate how your Proportional ($P$), Derivative ($D$), and Integral ($I$) gains reject external environmental forces.  
"""

# Task 1 Simulation Configuration Settings
t_max_drone = 12.0
dt_drone = 0.05
drone_time_steps = np.arange(0, t_max_drone, dt_drone)
target_altitude = 10.0  # Target distance marker

# Global caching arrays to pass runtime telemetry logs to the animation engine
drone_t_log = []
drone_z_log = []

def simulate_drone_flight(Kp, Kd, Ki, wind_setting):
    global drone_t_log, drone_z_log

    # Core system state variables
    altitude = 0.0
    velocity = 0.0

    # PID feedback registers
    accumulated_error = 0.0
    previous_error = 0.0

    drone_t_log = []
    drone_z_log = []

    for t in drone_time_steps:
        error = target_altitude - altitude
        accumulated_error += error * dt_drone
        derivative_error = (error - previous_error) / dt_drone if t > 0 else 0.0

        # Standard PID control signal tracking law
        control_thrust = (Kp * error) + (Ki * accumulated_error) + (Kd * derivative_error)

        # Apply environmental wind disturbance step input strictly after 6 seconds
        active_wind = wind_setting if t >= 6.0 else 0.0

        # State acceleration physics: thrust - gravity + wind force
        gravity_constant = 9.81
        acceleration = control_thrust - gravity_constant + active_wind

        # Euler integration step updates
        velocity += acceleration * dt_drone
        altitude += velocity * dt_drone

        # Hard ground boundary limiter
        if altitude < 0.0:
            altitude = 0.0
            velocity = 0.0

        drone_t_log.append(t)
        drone_z_log.append(altitude)
        previous_error = error

def trigger_drone_plot(button_event):
    with drone_ui_output:
        clear_output(wait=True)

        # Execute flight logic processing loop utilizing the slider values
        simulate_drone_flight(w_kp.value, w_kd.value, w_ki.value, w_wind.value)

        # Render static analytical performance evaluation figure
        fig, ax = plt.subplots(figsize=(10, 4))
        ax.plot(drone_t_log, drone_z_log, color='blue', linestyle='-', linewidth=2, label='Drone Flight Path')
        ax.axhline(target_altitude, color='red', linestyle='--', linewidth=1.5, label='Target Altitude (10m)')
        ax.axvline(6.0, color='green', linestyle=':', linewidth=1.5, label='Wind Introduced (t=6s)')
        ax.set_title("Drone Altitude PID Step Response & Disturbance Recovery Profile")
        ax.set_xlabel("Time Duration (seconds)")
        ax.set_ylabel("Altitude Position (meters)")
        ax.grid(True)
        ax.legend(loc='lower right')
        plt.show()

# Setup interactive dashboard UI controls
w_kp = widgets.FloatSlider(value=15.0, min=0.0, max=40.0, step=0.5, description='Gain P:')
w_kd = widgets.FloatSlider(value=5.0, min=0.0, max=20.0, step=0.1, description='Gain D:')
w_ki = widgets.FloatSlider(value=0.1, min=0.0, max=10.0, step=0.1, description='Gain I:')
w_wind = widgets.FloatSlider(value=-6.0, min=-15.0, max=15.0, step=0.5, description='Wind Force:')
btn_run_drone = widgets.Button(description="Run Simulation and Plot", button_style='info')

btn_run_drone.on_click(trigger_drone_plot)
drone_ui_output = widgets.Output()

# Pack UI controls vertically
display(widgets.VBox([w_kp, w_kd, w_ki, w_wind, btn_run_drone, drone_ui_output]))

"""# **Task 1 – Drone Flight Animation**"""

# Force clear any previous hidden background plot windows
plt.close('all')

if not drone_z_log:
    print("Error: Run the simulation cell above first!")
else:
    # Use a clean, explicit layout aspect ratio
    fig, ax = plt.subplots(figsize=(4, 5))
    ax.set_xlim(-1.5, 1.5)
    ax.set_ylim(0, 15)
    ax.axhline(target_altitude, color='red', linestyle='--', alpha=0.7, label='Target Setpoint')

    # Corrected tuple unpacked line initialization
    drone_body_line, = ax.plot([], [], color='black', linestyle='-', marker='s',
                               markersize=10, markerfacecolor='cyan', linewidth=4)
    telemetry_string = ax.text(-1.3, 13.8, '', fontsize=10, fontweight='bold')
    ax.legend(loc='lower left')
    ax.grid(True)

    def frame_init():
        drone_body_line.set_data([], [])
        telemetry_string.set_text('')
        return drone_body_line, telemetry_string

    def frame_advance(frame_index):
        z_pos = drone_z_log[frame_index]
        t_val = drone_t_log[frame_index]

        drone_body_line.set_data([-0.4, 0.4], [z_pos, z_pos])
        telemetry_string.set_text(f"Time: {t_val:.2f}s\nAlt: {z_pos:.2f}m")
        return drone_body_line, telemetry_string

    # Render with JSHTML conversion directly inside the cell frame output window
    flight_anim = FuncAnimation(fig, frame_advance, frames=len(drone_t_log),
                                init_func=frame_init, interval=40, blit=True)
    plt.close(fig)
    display(HTML(flight_anim.to_jshtml()))

"""# **Task 2 – Autonomous Boat Path Tracking**"""

plt.close('all')

if not boat_x_log:
    print("Error: Run the boat simulation dashboard cell above first!")
else:
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.set_xlim(-5, 25)
    ax.set_ylim(-5, 25)
    ax.plot(desired_x_track, desired_y_track, color='blue', linestyle=':', label='Target Path Blueprint')

    path_trail_line, = ax.plot([], [], color='red', linestyle='-', alpha=0.6, label='Tracked Footprint')
    vessel_dot_marker, = ax.plot([], [], color='magenta', marker='o', markersize=8, label='Boat Position')
    ax.set_aspect('equal')
    ax.legend(loc='upper left')
    ax.grid(True)

    # Downsample frame rates by skipping every second frame index to prevent UI stuttering
    frame_stride = 2
    frame_indices = list(range(0, len(boat_time_domain), frame_stride))

    def boat_init_canvas():
        path_trail_line.set_data([], [])
        vessel_dot_marker.set_data([], [])
        return path_trail_line, vessel_dot_marker

    def boat_update_canvas(f_idx):
        path_trail_line.set_data(boat_x_log[:f_idx], boat_y_log[:f_idx])
        vessel_dot_marker.set_data([boat_x_log[f_idx]], [boat_y_log[f_idx]])
        return path_trail_line, vessel_dot_marker

    vessel_anim = FuncAnimation(fig, boat_update_canvas, frames=frame_indices,
                                init_func=boat_init_canvas, interval=50, blit=True)
    plt.close(fig)
    display(HTML(vessel_anim.to_jshtml()))

"""# **Task 2 – Autonomous Boat Guidance Animation**

This renders the boat tracking its assigned target paths with dynamic current compensation active
"""

if not boat_x_log:
    print("Error: Please execute a successful simulation run using the boat dashboard button above first!")
else:
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.set_xlim(-5, 25)
    ax.set_ylim(-5, 25)
    ax.plot(desired_x_track, desired_y_track, color='blue', linestyle=':', label='Target Path Blueprint')

    path_trail_line, = ax.plot([], [], color='red', linestyle='-', alpha=0.6, label='Tracked Footprint')
    vessel_dot_marker, = ax.plot([], [], color='magenta', marker='o', markersize=8, label='Boat Vehicle Position')
    ax.set_aspect('equal')
    ax.legend(loc='upper left')
    ax.grid(True)

    # Strided index framing optimization to guarantee quick notebook cell compilation times
    frame_stride = 2
    frame_indices = list(range(0, len(boat_time_domain), frame_stride))

    def boat_init_canvas():
        path_trail_line.set_data([], [])
        vessel_dot_marker.set_data([], [])
        return path_trail_line, vessel_dot_marker

    def boat_update_canvas(f_idx):
        path_trail_line.set_data(boat_x_log[:f_idx], boat_y_log[:f_idx])
        vessel_dot_marker.set_data([boat_x_log[f_idx]], [boat_y_log[f_idx]])
        return path_trail_line, vessel_dot_marker

    vessel_anim = FuncAnimation(fig, boat_update_canvas, frames=frame_indices, init_func=boat_init_canvas, interval=50, blit=True)
    plt.close(fig)
    display(HTML(vessel_anim.to_jshtml()))

"""# **Creative Bonus Task – Drone Figure-Eight Trajectory Simulation**

To satisfy the creative bonus component, this code uses continuous parametric mapping equations ($A \cdot \sin(\omega t)$, $B \cdot \sin(2\omega t)$) to drive a drone along a smooth figure-eight path while compensating for multi-axis cross-winds
"""

plt.close('all')

fig, ax = plt.subplots(figsize=(8, 5))
ax.set_xlim(-12, 12)
ax.set_ylim(-7, 7)
ax.plot(blueprint_x, blueprint_y, color='blue', linestyle=':', label='Target Path Line')

f8_trail_line, = ax.plot([], [], color='green', linestyle='-', alpha=0.6, label='Drone Trajectory Path')
f8_drone_node, = ax.plot([], [], color='red', marker='o', markersize=8, label='Drone Node Location')
ax.legend(loc='upper right')
ax.grid(True)

def f8_init_canvas():
    f8_trail_line.set_data([], [])
    f8_drone_node.set_data([], [])
    return f8_trail_line, f8_drone_node

def f8_update_canvas(frame_idx):
    f8_trail_line.set_data(f8_x_history[:frame_idx], f8_y_history[:frame_idx])
    f8_drone_node.set_data([f8_x_history[frame_idx]], [f8_y_history[frame_idx]])
    return f8_trail_line, f8_drone_node

f8_flight_animation = FuncAnimation(fig, f8_update_canvas, frames=len(time_domain_f8),
                                    init_func=f8_init_canvas, interval=40, blit=True)
plt.close(fig)
display(HTML(f8_flight_animation.to_jshtml()))

"""# **Figure-Eight Animation Profile**"""

fig, ax = plt.subplots(figsize=(8, 5))
ax.set_xlim(-12, 12)
ax.set_ylim(-7, 7)
ax.plot(blueprint_x, blueprint_y, color='blue', linestyle=':', label='Target Path Line')

f8_trail_line, = ax.plot([], [], color='green', linestyle='-', alpha=0.6, label='Drone Trajectory Path')
f8_drone_node, = ax.plot([], [], color='red', marker='o', markersize=8, label='Drone Node Vehicle Location')
ax.legend(loc='upper right')
ax.grid(True)

def f8_init_canvas():
    f8_trail_line.set_data([], [])
    f8_drone_node.set_data([], [])
    return f8_trail_line, f8_drone_node

def f8_update_canvas(frame_idx):
    f8_trail_line.set_data(f8_x_history[:frame_idx], f8_y_history[:frame_idx])
    f8_drone_node.set_data([f8_x_history[frame_idx]], [f8_y_history[frame_idx]])
    return f8_trail_line, f8_drone_node

f8_flight_animation = FuncAnimation(fig, f8_update_canvas, frames=len(time_domain_f8), init_func=f8_init_canvas, interval=40, blit=True)
plt.close(fig)
display(HTML(f8_flight_animation.to_jshtml()))